# File: environment/conda.yml
name: mlops-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy==2.3.3
  - pandas==2.3.3
  - scikit-learn==1.7.2
  - joblib==1.5.2
  - pip:
      - azureml-defaults
      - fastapi==0.119.0
      - uvicorn
