# Azure ML Training Pipeline
# This pipeline automates model training, validation, and registration

$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: fraud_detection_training_pipeline
description: End-to-end pipeline for fraud detection model training

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster

inputs:
  training_data:
    type: uri_folder
    path: azureml:fraud_training_data:1

outputs:
  model_output:
    type: mlflow_model
    path: azureml://datastores/workspaceblobstore/paths/fraud-model-output

jobs:
  data_prep:
    type: command
    component: azureml:data_prep@latest
    inputs:
      raw_data: ${{parent.inputs.training_data}}
    outputs:
      processed_data: 
        type: uri_folder
    command: >-
      python src/features.py 
      --input-path ${{inputs.raw_data}} 
      --output-path ${{outputs.processed_data}}

  train_model:
    type: command
    component: azureml:model_training@latest
    inputs:
      training_data: ${{parent.jobs.data_prep.outputs.processed_data}}
    outputs:
      model:
        type: mlflow_model
    command: >-
      python src/train.py 
      --data-path ${{inputs.training_data}} 
      --model-output ${{outputs.model}}

  evaluate_model:
    type: command
    component: azureml:model_evaluation@latest
    inputs:
      model: ${{parent.jobs.train_model.outputs.model}}
      test_data: ${{parent.jobs.data_prep.outputs.processed_data}}
    outputs:
      evaluation_results:
        type: uri_file
    command: >-
      python src/evaluate.py 
      --model-path ${{inputs.model}} 
      --test-data ${{inputs.test_data}} 
      --metrics-output ${{outputs.evaluation_results}}

  register_model:
    type: command
    condition: ${{parent.jobs.evaluate_model.outputs.evaluation_results.accuracy > 0.85}}
    inputs:
      model: ${{parent.jobs.train_model.outputs.model}}
      evaluation_results: ${{parent.jobs.evaluate_model.outputs.evaluation_results}}
    command: >-
      az ml model create 
      --name fraud-detector 
      --version ${{system.pipeline_run_id}} 
      --path ${{inputs.model}}