# File: .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [main]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pytest -q || true
      - name: Build Docker image
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: |
          docker build -t $ACR_NAME/fraud-model:ci-${{ github.sha }} .
          echo "docker build done"
      - name: Push image to ACR
        if: always()
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin
          docker tag $ACR_NAME/fraud-model:ci-${{ github.sha }} $ACR_LOGIN_SERVER/$ACR_NAME/fraud-model:ci-${{ github.sha }}
          docker push $ACR_LOGIN_SERVER/$ACR_NAME/fraud-model:ci-${{ github.sha }}
