---
name: CI/CD Pipeline for Fraud Detection ML Model

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AZURE_ML_WORKSPACE: mlops-scotia-ws2
  RESOURCE_GROUP: mlops-rg
  ENDPOINT_NAME: scotia-fraud-detection-endpoint
  DEPLOYMENT_NAME: fraud-deployment

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run unit tests
        run: pytest tests/ -v --cov=src/ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy

      - name: Run Black formatter check
        run: black --check src/

      - name: Run Flake8 linter
        run: flake8 src/

      - name: Run MyPy type checker
        run: mypy src/

  build-and-test-docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fraud-api:latest .

      - name: Test Docker container
        run: |
          docker run -d -p 8080:8080 --name fraud-api-test fraud-api:latest
          sleep 10
          curl -X POST http://localhost:8080/predict \
            -H "Content-Type: application/json" \
            -d '{"features": {"amount": 100, "hour_of_day": 14,
                 "avg_monthly_spend": 500,
                 "customer_tenure_days": 365,
                 "num_prev_tx_24h": 5}}'
          docker stop fraud-api-test

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: [build-and-test-docker]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure ML CLI
        run: az extension add -n ml

      - name: Deploy to Azure ML
        run: |
          az ml online-deployment update \
            --name ${{ env.DEPLOYMENT_NAME }} \
            --endpoint-name ${{ env.ENDPOINT_NAME }} \
            --file deployment.yml \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --workspace-name ${{ env.AZURE_ML_WORKSPACE }}

      - name: Smoke test Azure ML endpoint
        run: |
          echo '{"features": {"feature1": 0.5, "feature2": 1.2,
                 "feature3": 0.8}}' > test_data.json
          az ml online-endpoint invoke \
            --name ${{ env.ENDPOINT_NAME }} \
            --request-file test_data.json \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --workspace-name ${{ env.AZURE_ML_WORKSPACE }} \
            --output-path response.json
          cat response.json

      - name: Upload deployment logs
        uses: actions/upload-artifact@v3
        with:
          name: deployment-logs
          path: |
            response.json
